Quarto Python example
sol-eng/python-examples pull request #80
Opened 2022-11-02 23:06 UTC by leesahanders

2022-11-02 23:34 UTC, leesahanders commented
Tested deployment (using rsconnect) just to make sure nothing broke going from my personal repo into this one: <https://colorado.rstudio.com/rsc/connect/#/apps/ba8c450a-0779-4aad-bad5-01875b3d9dfd/access/5785>

2022-11-03 16:27 UTC, edavidaja requested changes
Looking good!

A few things:
- could you remove the files in `.ipynb_checkpoints/` from the manifest?
- I think (but am not certain) that the `quarto-python-jupyter_files` and `quarto-python-files` should be created at render time; if so, could you remove them from the manifest?
- could you generate the requirements file yourself? If you did it in a virtual environment the results should be the same, but I don't want to assume.
- if you're going to [hotlink to the image on wikimedia](https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia/technical#Hotlinking) you may want to do so in their recommended fashion. Alternatively, you may want to make the images part of this folder.

2022-11-15 16:59 UTC, leesahanders commented
Deployments working, woohoo!

git backed: https://colorado.rstudio.com/rsc/connect/#/apps/9dbe7eb2-f51b-478e-b776-ce9dfce7daa2/access/5811 
rsconnect: https://colorado.rstudio.com/rsc/connect/#/apps/d786f16e-c19d-4e8e-ae42-8e24e54bae0e/access/5812

2022-11-15 20:50 UTC, edavidaja commented on README.md
> +```
```suggestion

```

I'm not sure this is necessary here.

2022-11-15 20:58 UTC, edavidaja approved these changes
I trimmed some stuff from the top level readme but otherwise I think this is good to go.

2022-11-15 20:58 UTC, merged